version: "2.3"
services:
    furnace-monitor:
        container_name: "furnace-monitor"
        image: "danielkneip/furnace-monitor:latest"
        volumes:
            - ./:/app/config:ro
            - ./data:/app/data:rw
            - ./sys:/app/sys:rw
        restart: "always"
